# fly.toml file generated for socialite-media-app on 2023-02-24T09:00:27-06:00

app = "socialite-media-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  MONGODB_URI = "mongodb+srv://babrigo:812002@sociliitecluster.mmu5dpl.mongodb.net/socialiteapi?retryWrites=true&w=majority"
  CLIENT_ORIGIN = "https://socialitemedia.netlify.app"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
